# ## Задача: Инвентори Kubernetes-кластера
# - **Статус**: В процессе
# - **Описание**: Описать группы хостов и их адреса для Ansible-плейбуков.
all:
  vars:
    ansible_user: enemirov
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3
  children:
    control_plane:
      hosts:
        k8s-scp-01:
          ansible_host: 10.255.106.10
        k8s-scp-02:
          ansible_host: 10.255.106.11
        k8s-scp-03:
          ansible_host: 10.255.106.12
    workers:
      hosts:
        k8s-wkn-01:
          ansible_host: 10.255.106.13
        k8s-wkn-02:
          ansible_host: 10.255.106.14
        k8s-wkn-03:
          ansible_host: 10.255.106.15
    metallb:
      hosts:
        k8s-mlb-01:
          ansible_host: 10.255.106.16
        k8s-mlb-02:
          ansible_host: 10.255.106.17
        k8s-mlb-03:
          ansible_host: 10.255.106.18
    nfs:
      hosts:
        k8s-nfs-01:
          ansible_host: 10.255.106.19
    k8s_cluster:
      children:
        control_plane:
        workers:
        metallb:
