# ## Задача: Роль base_os
# - **Статус**: В процессе
# - **Описание**: Дефолтные параметры подготовки ОС перед установкой Kubernetes.
base_os_packages: []

base_os_packages_common:
  - curl
  - vim
  - wget
  - tar
  - unzip
  - ca-certificates
  - chrony

base_os_packages_by_family:
  RedHat:
    - conntrack-tools
    - iproute-tc
    - nfs-utils
    - firewalld
    - policycoreutils-python-utils
  Debian:
    - conntrack
    - iproute2
    - nfs-common
    - firewalld
    - policycoreutils

base_os_timesync_service_by_family:
  RedHat: chronyd
  Debian: chrony

base_os_chrony_conf_by_family:
  RedHat: /etc/chrony.conf
  Debian: /etc/chrony/chrony.conf

base_os_disable_zram_distributions:
  - RedOS

base_os_disable_zram_major_versions:
  - "8"

base_os_manage_package_updates: true
base_os_disable_swap: true
base_os_disable_zram0: true
base_os_update_all_packages: true
base_os_manage_time: true
base_os_manage_hostname: true
base_os_manage_hosts_file: true
base_os_manage_networkmanager_dns: true
base_os_networkmanager_ignore_auto_dns: true
base_os_manage_resolv_conf_symlink: false
base_os_resolv_conf_target: /run/systemd/resolve/resolv.conf

base_os_kernel_modules:
  - overlay
  - br_netfilter

base_os_sysctl:
  net.bridge.bridge-nf-call-ip6tables: 1
  net.bridge.bridge-nf-call-iptables: 1
  net.ipv4.ip_forward: 1
  vm.swappiness: 0
